basePath: /
components:
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: X-Auth-Token
      type: apiKey
info:
  contact:
    email: frikky@shuffler.io
    name: '@frikkylikeme'
    url: https://twitter.com/frikkylikeme
  description: Automated generation of Carbon Black Response
  title: Carbon Black Response
  version: '1.0'
  x-categories:
  - EDR
  x-logo: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK4AAACuCAYAAACvDDbuAAAVJUlEQVR4Xu2dCZRNV9bH/69KSVBlDmltSkg0YgihffkIWtNBgqxuc5RGGUIVqlRaIV8anZHEELrN8zzEFKFXQpAgSkIEWSLELIl5KFMp6n3rf149XpWqd89975VyvH1XrKzEvffsu/fv7rfPPvvs64jIX9CZlHQJDjggh2jAFA04BFxTTCVyempAwBUejNSAgGuk2URoAVcYMFIDAq6RZhOhBVxhwEgNCLhGmk2EFnCFASM1IOAaaTYRWsAVBozUgIBrpNlEaAFXGDBSAwKukWYToQVcYcBIDQi4RppNhBZwhQEjNSDgGmk2EVrAFQaM1ICAa6TZRGgBVxgwUgMCrpFmE6EFXGHASA0IuEaaTYQWcIUBIzUg4BppNhFawBUGjNSAgGuk2URoAVcYMFIDAq6RZhOhBVxhwEgNCLhGmk2EFnCFASM1IOAaaTYRWsAVBozUgIBrpNlEaAFXGDBSAwKukWYToQVcYcBIDQi4RppNhBZwhQEjNSDgGmk2EVrAFQaM1ICAa6TZRGgBVxgwUgMCrpFmE6EFXGHASA0IuEaaTYQWcIUBIzUg4BppNhFawBUGjNSAgGuk2URoAVcYMFIDAq6RZhOhBVxhwEgNCLhGmk2EFnCFASM1IOAaaTYRWsAVBozUgIBrpNlEaAFXGDBSAwKukWYToQVcYcBIDQi4RppNhBZwhQEjNSDgGmk2EVrAFQaM1ICAa6TZRGgBVxgwUgMCrpFmE6EFXGHASA0IuEaaTYQWcIUBIzUg4BppNhFawBUGjNSAgGuk2URoAVcYMFIDAq6RZhOhBVxhwEgNCLhGmk2EFnCFASM1IOAaaTYRWsAVBozUgIBrpNlEaAFXGDBSAwKukWYToQVcYcBIDQi4RppNhBZwhQEjNSDgGmk2EVrAFQaM1ICAa6TZRGgBVxgwUgMCrpFmE6EFXGHASA0IuEaaTYQWcIUBIzUg4BppNhFawBUGjNSAgGuk2URoAVcYMFIDAm6AzeaEE/znnsMBOOAI8GjBezsB10/bu0C9S2pISAgeffRR8N/u40ZyMm6lpKQbyeG4+/d+ihCUlwu4Ns3uCarD4UDuR/OgSuVKKFGihPpTpkwZPFa0KMLCwlx3djhw4cIFHD16FKdOncIvv/yCn376Cb/99htSU1PvnBMIb+x6fTJz9+kfkn7ffVYgxrWpwoCcLuBqqtENLGEtVqwYqlSpgmbNmqFSxYoo8fvfo2jRooiIiEDu3LkRGhqaLii4nZqKW7du4fr16zhz5oyC9vChQ9i4aRO2bNmCw4cP4/bt26QcvL8vh5IPQNVq1VC/bl088sgjcP+/dPdzArlyheL4yV+wdOlS3Lx508gQRsDVoMTpTFVAVq9WDY3+/Ge0adMGTzzxBPLly4dcuXJp3OHeUwjq9WvXcObsWaxauRIrVq7Ejh07kJSUpLy0XU/ofrFiYmIwdOhQ5MmTB0569AzvAaMaPstXX32FTp06qV8AE8MWAdcLdoSBdq9T53/QvkN7NGvaVAHrGb/6RG2Gi5xOp/LC69evx4IFC7Bm7Vr1W27H+7rBjY2Nw7/+NVy9VN6OL7/8Eu3btxdwA2HAB+kehIngNGnSWHmwGjVqKE+VnQe98IEDB/DPf76JJUuWwiWD3iQuPbjDkC9fuICbncZ60O7tBiBP3rzoHBmJgQMHomzZsvdVzF9//RUffvghJkyYgGvXrmnBK+DeVxM9eIPRy1WsVBGvx8ejVatWKFSoUI4IeenSJSxdsgTvjxiBAwcPWsa8Am6OmOnBGJSTsPDwcIwbN05NXJgdyMkjOTkZkydPRnx8PG7eTPEa8wq4OWmpHBxbTcQcDgwZPFiFBwT4QTjOnjmDAfHxmD17joDrYRDJKqhkvCsHypj2/fffR/HixW0zS+945coVnDx5EvyZ538z7GC6rECBAihZsqT6N/Ordo89e/aga9eu+Pbbb7OMd8Xj2tXqQ3G+Ey1btsQ777yDihUr2noiTp527tiBzVs2IzFxO44dO3YHXN6I4HJhgmm0OnXqoEGDBnj22WfVsrDuwRW2WbNmITo6BteuX8s03hVwdbX5kJzHuLZgoUKYO2cumjdvpv1U9KZnz57F9Bkz1Oz/xPHjaatfWd+CMTMB5iJBZGQkChYsqD0eFwoGxMVh0eLFadekX1kQcLVV+XCcSHAJ0rvvvmuZtHc/MfOtidsSMWz4cKxb97mr5kBjtcsNFwFu166diqUrVaqkNQnki8LVro4dO+LEiRP3hAwC7sPBo9ZTEIYiRYtgxfLlqFu3rtY1KSkpWPXJJxg2dCj27N2rrvFleTbE4UC9evUwePBgNGrUSAtexs49unfH4iVL7hu4KvpX1W9pZTkaL6iWIv08KagnZ/S2UVHdMHrUaIRHRGipctu2bYiK6o4fftibNsv3oyjG6UTDBg0xddpUPPnkk5bj09MzVRcbG5st4KavfAtBSIgDjpBQhDqAMAeQ6gRSnE6k8s/t22ry6Xpz7ddWWD6sxQlBCy6NlC9vXkycOBGvvvqqlh4vXrqEQQkJmDhpkm0vm9kAlIGed+TIkSpcuVMK6UUa1jM0btLEtRzsUUHjT6hA8OhVw8Jyo0SJ36lfn1q1aqmJaunSpZE3Tx51Cn9bbqak4Pjx42pCuuv777F9+3a1QEKQ4Qi5b6XyQQ3uS82bY/z48aqGVudgBVdkp05ISrpiqwDG273p9QnKzBkzUK58eUsx9v+4H63btAZTZJ51DP6Ay/z1c7VqqXQggX366adV6s5bkQ9fnKtXr2Lfvn1Ys2YNZs6ciSNHjtw37xuU4NLIucNyY8qUyWqyo7NCxmLwXr16YfHixVq1A5YEpp1AWSLCwzF33jy0ePlly8suXryI6OhozJs3LyDgsi6iS5cu6NOnjyrbDPFhtZAAf/3115g6dSqWL1+uvLLduN/ywTOcEJzgOlNRqVJlzJ07R+VUdY5169ahQ4cOOHPmbMC8rZr3wInQkBDExcaiU2Sk5UvEDMaoUaMwY8YMv8DdtGkTunXrhs6dOytoCxcurKMGr+cwJTh8+HBMnTZNTeWyE96gBfell15SSX0dg3FSRIPwT/bEca7lZh3Pz/NSODFKTfUrxiW4W7dsQa/XXgtoIRHLMvlCMHWXPbpKmw9G5C/oTEq6lK1vh9+vcoBvwPgsJroPPhw1SmtCRGMwtt2WmBjQMMHzsTJuuvT6yJnM4u3GuKdPn1b558cffzzA2gW2bt2qwirG4dkFb1B6XP5Ajx83Tnkbq90MhJx5265duuL8+XPZBq6/9NgF1+t4zvS71ezsxOB9+UJs3LAB/fr3x969TBvqFcPb0UGQggssX7EcLVu0sNQVwwQu6faPjVVLutkZt1kK4+WEQIDL/W5cleMvDBc7eISG5kLJUiXxhwoVVFilu8fuxo0bKs03dNgwBXKg9RaU4DInyVlw7dq1LVnhStnbb7+NYcOGZYvnsBRA8wR/wCVYzMvOmj0bO3fuxO49e1Slmyt160CZ0qXxXM2aaPKXv6BFixba1XPfffcdWrdpg59ZCB9grxt04Lrrbnd//z2eeeYZSyy4pfzNN9/EBx98EHDlWw5u4wRfweWvyCerV+P/hgzB3h9+SBuRbXdcPtIz9mZJJgvshwwZorWdiffu2bMnpk2bHtBMjHqfgm1y5tqACOzevVsLXK6WxQ8YgGnTpj2U4H722Wfo3bs3fv75Z69L2K6ahVR1DusrWHDPfXlWB+/folUrJN+4EdBwISjBDQkNAT1u5cqVrfQOzr6Z52TzjED/3FkObuMEXzwuF1VYoL5ixQrtZ+NKX/ny5bFkyRJUr17dUkLWJ9d74QUcO3osoF43iMHdjcqVK1kqnitLrCP4+OOPtY1redNsOMEXcKdMmYI+0dFgHK87eXJ73h49e2LcRx9ZbtnnLxbriKdPZ7gQuOxCEIMb3B6XW4u4arZo0SLbQKly0CKFwaYirCf2djDOnTRpIvr0iVFddXRfEKt3OyjBlRgXKqZlVRzLNO16Qvcy9XvvvYe4uDjLXPh/165FZOcuOHPmlO2xsgI4+MBN280b7FmFzZs3o1379jiZyW4KK2+n5mnOVAX+6NGjVcM/bweb+vXo0QOs97D7kgi4HhrwNY+b3QXT6dervOOT8SfXbozLvWtR3brhypWrPk2aCG6d55/H7Jkz8dRTT3kV9vz58ypz4UtYIuCm04BTTbZeeeUVS+fCGI3F5v37x6pWoXaXPy0HuHOCq9BG5/6MMV27D+7uvrADLidjfCadRiNZyU9w/1CxIhYuWIBq1ap5fUxmL1iKOX/+fPG4+kBkdqZT/cQxW2BVq8Cr1zJGi4xUu3oD9VPnKRUh4O5fpqbyFyiQrsN5RukdISHY/+OPqnD7KvuKpcFrB1z2xOUWoISEQbh1+5ZPEybKTE/L7pI1a9b0ag5mFvr17YvZs2cHrOgm6GJcd3zGFZ2PNNI5PJ9bVVhszW0z2QUu+zosXLhQq98Cc8osHbx8OemOh7YDLjMKY8aMUStgbDrty0zfDrise2A3nmlTpwZsh0TQgtu4cWPlAXTL+kaMHImB//hHwBTvdlFqCRrA66+/jrfeekurzJK1E2+88UY6WeyAS4/77/HjMTAhASkMf3zYKWYH3IuXLqJf337icf0LE1wz4nLlymP+/HlahTYc75tvvkGHjh1x8MCBgHpdAheeL58qcHmlVSvLGJcx96BBg1Tlla97zhirT540CbFxcZbN9LzFuNxMyV+JqlWrSozrL5Q61xOWsFy5MGb0aER17265+sN7stUSveJ/JkxQQ/jipTKNtp2paumUAFSoUMFSfHYuj4qKwqeffuozuBxkydKlKqvgGW5YDu5xgmuTZz3MmDFdLQF7O5hVeI379TLpB2FnTM9zgzJUcMe5L9R7ARMmTrBc/XErjJX9nTv/HQcPBsbrutNfbwwZgoSEBK1OOlwwYJiTMY1lJ1Tg82zZuhUd2rdXvc58idvdeVy+/EUs8riHDh1C9+7d8cUXX/g0VmZwBy+4aT0Nxo4dq1I1OgcnNdyoyPiSTTH89brughXmN9mq3/JwOlWvMk7MMsJmF1x+voolitwbZhdc98oZw5X+/fqBmY6sQwqnKpv8e+fOuHDhomUoZKmDtBOCFly312Uud9KkSXjssce0dMYMQ9+YGKxctcqvnayElg1AWKDOzjQ63RuvXrmCPtF9MGvWbL/BZfE4vaAvxS/MIZctWwbccMmGId4OxtNMvcUNGOD3iy6hQpoG6Dn4WSXGlzo9DXiZ2i2wc6dqJDJv/gLcSrlp32M5U1WfXDa9Yy7ZasnUbTDWELdt1w4/7tvnN7i858JFi5T3Vt+ZsJFZILjx8QNUW1ar7jtZ9YHQ8hJeTgpqj+v2uuyXQBB1v/dAw7HckcXlI0aMwJWrV12LBmkf18sMAs+dBOx2zi/50OPlz59fy4aXL18Gi1r4TYjM9nDZDRU46Llz59RSLGtrdfsg8NmrV6+mFkCsVsw4BusUWI978sTJgIUJvK+AC1fX8NGjRimQ7HQMZ8y7a9cuzJk7B+s+X49Dhw8h5ebNTEHkCl2p0qXxp4YNVcGJ3c9PEZS+ffsiSe0Fu7fRni/gUlBujGR67eNly5Tc3jwvwxt2ax8zZixa/+2vCNX4OCGXljmH8HWhI6u3OujBdXtd5iQ5UeOM3e7Bn9o9u/cgcXuiagLHlSLPmgNCy0+o1q9fX/XmYl8uOwebOnNy87mX6ipfwaUH3b49EQkDE9QnWhW8GQq+3ffOFRaGQQMHIi4+HgU1nuFmcrL6COCy5ctth1NW+hFwPeLdF+rVUyEDIfPl4IoUIXZ9l/fuQXDpyfNq7NHKOC7vyaXpQYMHu4p8sohFfQXXHbfv+m6XChlWrFqJn/bvv9tClJ8DCAtD82bN8LfWbVTXdh1oed/ExETVwJrN8OxmLqz0L+B6gMs4tWWrVhg7Zox2B0crBfvz92zduWLVKvTp3Vt9MtWb8f0B1y2j+yPZ7K1w5MhRJCffUDna0qVKoVSpUqqvgk71mjt+Zi0EP3elGz/b0ZWA66Et94JATHS02smqW8dgR+G657qzFzExfbFt29eWHssOuO6ySG+Vce6mzbqgej4XyybZlI+1EBcDmLv1HEPAzUASAeBXctq2bauS6zo7gXVh1D2P0LISjVmEDRs33uli7+16O+CyLSi37rCUks8a6IP53Z69eoG9fH0BX0ceATcTLXH2zOO552qptFWjRn/SWiDQUbjVOYSKsSZX5/jNNN1dF3bAZWqNFWZs4Mw8biAPfheje1SUim+zq+Ed5RVws7CaG4QiRYpi0KAEV5F3/vxarUB9AYFe9tSpU6pqi7laxpt2JjR2wGWPMO5+oFdnDNqgfn2fGjpnfE42uONOkfXr12m/cL7oSsDV0Bq9Lzu2tGvTFi+3bIH69eqhcJEiGlfqn3Lh4kVs3LgRixctwrJly8BMgh1oOVJ6cId7LdghuAMTBmHCf/6N2n/8IxjTN23aFEV8fC42uFuzdi1mz5qF1atXBzxnm5kmxeNq8OWCAsqwNWvUwPP/+7xKDz1ZrpxKcenUGWScvDAk4OydO1/5Z9u2RLWS5WvvATe47EvLSjOuzt35Ko7H4Iw5mbIbOnQYpk+fpv6GvyT8ZBU7oteuVUt9OJBL4d4mb5yAsTEeF2Dmzp2rXjgu7+qGNhpq93qKgKupQc8lWxq/WLFiqhyyYcMGqFKlqgKFYHNxgSB7Gp0eiXHlhfPnVTniwYMHsWHjBlWczvDgTt7Xz88uUUZ+IadY8eKu8d2fc/J8RodDdTP/7dRpXE/7vKoLcKfy0iyaefHFF5Unzh8egfCIcESERyA0V6i6jvvczp47p3K97Av27Y4d6rnU4af8mqZwDRVsTe/sKCerc91pM4Lh3pkbHp4fZcuWVlVmBMCzLT49HL3R0WPHcPrUabUDI7u+Eeb5gnl3Wfd+m+zOtQ6H+owVQSxerDiKFy+mFlC4AMJfhRMnT+L2rVt3dhpnV+bAm/wCbgBIdocSWnmr++iV/H20LF+CB+AZBFx/rSvX54gGBNwcUbsM6q8GBFx/NSjX54gGBNwcUbsM6q8GBFx/NSjX54gGBNwcUbsM6q8GBFx/NSjX54gGBNwcUbsM6q8GBFx/NSjX54gGBNwcUbsM6q8GBFx/NSjX54gGBNwcUbsM6q8GBFx/NSjX54gGBNwcUbsM6q8GBFx/NSjX54gG/h8boSZtY12Y6QAAAABJRU5ErkJggg==
openapi: 3.0.0
paths:
  /api/v1/banning/blacklist:
    get:
      operationId: Ban_a_hash
      parameters: []
      responses:
        default:
          content:
            text/plain:
              schema:
                example: ''
                type: string
          description: default
      summary: Ban a hash
  /api/v1/binary:
    get:
      description: Carbon Black Response Binary Search
      operationId: Carbon_Black_Response_Binary_Search
      parameters:
      - description: Generated by shuffler.io OpenAPI
        in: query
        name: q
        required: true
        schema:
          type: string
      responses:
        default:
          content:
            text/plain:
              schema:
                example: ''
                type: string
          description: default
      summary: Carbon Black Response Binary Search
  /api/v1/process:
    get:
      description: Carbon Black Response Process Search
      operationId: Carbon_Black_Response_Process_Search
      parameters:
      - description: Query
        in: query
        name: q
        required: true
        schema:
          type: string
      responses:
        default:
          content:
            text/plain:
              schema:
                example: ''
                type: string
          description: default
      summary: Carbon Black Response Process Search
  /api/v2/alert:
    get:
      description: Search alerts
      operationId: Search_alerts
      parameters:
      - description: Generated by shuffler.io OpenAPI
        in: query
        name: q
        required: true
        schema:
          type: string
      - description: Generated by shuffler.io OpenAPI
        in: query
        name: rows
        required: false
        schema:
          type: string
      - description: Generated by shuffler.io OpenAPI
        in: query
        name: start
        required: false
        schema:
          type: string
      responses:
        default:
          content:
            text/plain:
              schema:
                example: ''
                type: string
          description: default
      summary: Search alerts
  /api/v2/alert/{alertid}:
    post:
      operationId: Update__Resolve_an_alert
      parameters:
      - description: Generated by shuffler.io OpenAPI
        in: query
        name: unique_id
        required: true
        schema:
          type: string
      - description: Generated by shuffler.io OpenAPI
        in: query
        name: status
        required: true
        schema:
          type: string
      - description: Generated by shuffler.io OpenAPI
        in: path
        name: alertid
        required: true
        schema:
          type: string
      responses:
        default:
          content:
            text/plain:
              schema:
                example: ''
                type: string
          description: default
      summary: Update  Resolve an alert
schemes:
- ''
servers:
- url: ''
tags:
- name: EDR
