basePath: /
components:
  securitySchemes: {}
host: api.hashdd.com
info:
  contact:
    email: frikky@shuffler.io
    name: '@frikkylikeme'
    url: https://twitter.com/frikkylikeme
  description: API for https://hashdd.com
  title: Hashdd
  version: '1.0'
  x-logo: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK4AAACuCAYAAACvDDbuAAAeO0lEQVR4Xu2dB5QVxdLHG8MzIWCOmDFnEXMCFRUBkWhGMJBMgApmQMmISFZUVFD0KYiyqIgBMStmRBFEFHNaJJjlnV8/a7/hvt17p3tmlu1v656zZ9OE7qp/V1fuKvXq1Vth9KMUCIwCVRS4gXFMh2spoMBVIARJAQVukGzTQStwFQNBUkCBGyTbdNAKXMVAkBRQ4AbJNh20AlcxECQFFLhBsk0HrcBVDARJAQVukGzTQStwFQNBUkCBGyTbdNAKXMVAkBRQ4AbJNh20AlcxECQFFLhBsk0HrcBVDARJAQVukGzTQStwFQNBUkCBGyTbdNAKXMVAkBRQ4AbJNh20AlcxECQFFLhBsk0HrcBVDARJAQVukGzTQStwFQNBUkCBGyTbdNAKXMVAkBRQ4AbJNh20AlcxECQFFLhBsk0HrcBVDARJAQVukGzTQStwFQNBUkCBGyTbdNAKXMVAkBRQ4AbJNh20AlcxECQFFLhBsk0HrcBVDARJAQVukGzTQStwFQNBUkCBGyTbdNAKXMVAkBRQ4AbJNh20AlcxECQFFLhBsk0HrcBVDARJAQVukGzTQStwFQNBUkCBGyTbdNAKXMVAkBRQ4AbJNh20AlcxECQFFLhBsk0HrcBVDARJAQVukGzTQStwFQNBUkCBGyTbdNAKXMVAkBSoMMCtUqVKmQRcsWJFkMTVQWdHgUyBCxhzARkFofxc1t/4O/evvvrq2VFAn5yXAqXxMPeGfIIlK6GTGXAZ8J9//mn+/vtv+8VntdVWs98FzLmgLg3k/G2NNdZQeK0CCggPowJGeCnDEZ7K76XtnMLDfLuq6/QyAy4T4kuk5pprrmnWW289s9Zaa9nva6+9tll//fXNv/71r5Lf1113XbP2OuuY9atWtddtvvnm5vPPPzeDBw82v//+u5W8Wa1gV8JVhusBWmnA5G8AGH5Uq1athC/8Dm8RNPCJ36tXr26f8cYbb5hly5aV/C8p/VIHLoP8+eefTe3atU3r1q3NFltsYdZZZ53/EgDV4R+JK0Qp7bsAlHsWLFhgzjvvPEsoIUjSSev9+SkA3QEZvOvWrZvZcMMN7e6JkEHYrKS6RWwT4W306QisX3/91bRv397yskaNGuavv/5KzIJMgLt48WJTp04d0717d7PllluWSF2X0QJUCDh37lxz9tlnW/ArcF0o6H8tdF+yZImpWbOmGTp0qNlss828eCi77Y8//miBu3DhQiuBKyxwWa0777yz6dq1q9ljjz2stIyj30SvEeB+/PHH5qyzzlLg+uPQ+U6A+8svv5iNN97Y9OjRw+y9995eKhrA5VkAFiwsWrTISuxcPdl5gOza9erVS9XXBPh+++03q58yWCSvrDyXAco97777rrnwwgstcFXHdaGg/7WAje19gw02sLvmwQcf7PUw4eHs2bPNtddea7755hurA1dY4KIPYWh16dLF1K1bNxFwX3rpJbsAMOYUuF74cb4J4YMxXLVqVXPJJZeY448/3vkZ0RtmzZplevXqZX744QcrgCokcGXAf/zxh+nStatp1LChHWiudVqIErJaX375ZdO5c2eVuIUIluL/Aa4YY+3atzdNTjkl0dNnzJhhBg4caI12vEUVFriA9KeffjJdL7/ctGzRwgu4Qqlp06ZZPYsJq8RNhJ/YNwNcDCj4eM4551gbI8nnqaeeMkOGDLEGH56JNFyaqeu4TBDrH0WcLR6XmI/E5TkQb0pRkenfr59VFcQvnISIem9hCgBceAb9W7ZsaT0CST6TJz9qRo4cYfVm3GMVGrhffvmlOf/8881FF13kpeNCKIgHcPv17avATYIcz3vRcxs3bmxtlSSfiZMmmdGjRlm9OS2XZiYSly0dRbxJkybm0ksvtZaki2dBrsU7MWHCBDNmzBi7xcRxqSUhsN77fxQQX279+vXNDTfckIg048ffZ+66686SaFuFlbgAF6dzgwYNzKWXXWZqVK/uBVy2lvHjx5uxY8cqcBNBx/1meIidgleob9++7g+I3IHgue+++6zgSUvdy0TiStj3yCOPtB4BfLo+Ehfgjhs3ztx9990K3ETQcb+ZLf3bb781hxxyiBk+fLj7AyJ33HHHHVYABQFcLMgDDzzQGmjbbLONF3CJwN1+++1m4sSJFrj6KT8KANzvvvvO5pwMGzasxKjyUddGjBhhHnzwQesVqvASF9AR7r388stNrVq1vIC7dOlSM3LkSPPYY48pcMsPs/ZNgKy4uNjysH///jb867JrRoc7YMAA8+ijj1oDOw39lmdnoipI2Hf77bc3V1xxhZ28y6TlWoDLap0yZYoCdxUAl2Qpck6Iem277bZOPAwWuLg+yCoiLW7//fd3mrQAF8LdfPPN5tlnn1XgljNw2dIRHKh5V199tdlrr72ceBgscAkZkgl01VVX2SQNlyCEALd48WLTp3dvQ9hXddzyRa5kiCF8UPcOOuggb+AS7kVVIPpZ4VUFoi5ESa655hpzxBFHeAOX4MOLL76owC1f3FojitRGgHvllVdaQ9tF3YsO96abbjJFRUUl/vw0ppKJjisDI4Bw/fXXm2OPPdYLuPiCSYd77733Ul2taRDu//sz0gQuwot8BZLI00iwycw4sw+uUsXqSERdiL74qApE39CRP/roIwVuOa+UNIGLjjx9+vRwgIsvl8yuJMAlkfnDDz9U4K4C4BIA2mijjcxll11mCCb5qgpBARc/4BdffGFu6t3bNG7USCVuOQMv6evYMcmpxsAmUYpkcl/gBqUqAFxKy3v36WNOadzYG7gqcZNC0O9+AS7l5506dUoEXDxLTz/9dBiqAsAlJxfgJpG4BDAomEzTleLHysp110rA7djJHF/fX+KSaPXCzJlW7UijwjdT40xUhRt69DDNmjb1krjEylntX331VSLgVta+ZHHyCsryq0rdGZ4AVIXjjjvOW1Xo0KGD9cXjWsO/n8YnM3cYwP36669tdhjlHy76kVxLdhLZ9wA4rsQVZkXbBgmh5G9ltX6K/j0tR3kaTIrzjNx5c0+UBtH5yLV8j/4cpZPUnUF36s5Q91x4GB1zx44dLXA33XTTig9c3CmUI2ORUr7jMukocFmtADgfcIX40qeM7zyDbYnv8rv4EIVhkmbHIivrb2n5HeOAz/UaGbOU2eTOW2hAphfJ/JKZRdEitGHe8kWLodWq/LdtltAD6cjPbdq2Nae1auXEw+hc4OErr7wSBnBF4mYJXGEEeRHiJ4ZZrGzyIzbZZBNTvUYNs+EGG9geV5Rbcw/WMq46IkNLly0zX37xhW0PxBeLJCqtCDVLryxXYGV1vSxU5iFFjcwbHXLfffe1rZOqVa9uE/jJ6mLe0bZJAJLryf5asOBTs2jR52bR54vMx/M+tq2Xogsa0Lc97zzTonlzb+AGJ3EJIND3iy/Cv3E/hSSulLoTmYMJSJOtttrKMo28iO22286WswM6CJ+v2yOA5zn4LPlO0OTd994z0596yhqF/I2PpOStahWCuctClV5e++23nzn88MPNrrvuamnB36F3nC6XgJ+5852kprfefts8//zz5sM5c+zvoiq0atnSG7hBSVwpUT/99NNtJxoahMRVF/IBl+cCJpiH4bDnnnuapk2b2tRJmAXAcnXY0vTd0nQ7WVgshuXLl5v58+ebqVOnmtdff71EXeEdq0J9kN2FcbEo2VEwmGiPhK9VqqBzhQNzz2eA5dKKuQPkOXPmmHvuuccuXlQFV4krPGRXo6nIW2+9ZZvnVXivQtrAhTF8kIh0/AOoDRs2tFlLSIVcA0x+97Gso4YODKAN1L333mtbZfK/tEqs4+5AbPOAicVKUn6z5s3Nccce+z+LtDQDLM47yroPXZhFi+qx++67x3nUSnyAVmT4denc2eab0NKp0gAXrwIqB2BBL0XCnnbaaTbjLJrqWJbHwInakYtzn4fuN2nSJFv0h9QrL/DCfOaN/nr00UebFi1a2KTuQp4S33mLfh9nwed7h0jcSgtcfIh0+0OqAlZ6NUSz8eOqH76MzAUwqsOtt95qDbu0urKUNTZJVEJ3b9asmTnmmGNWqtlKCq5CNElC20oNXPy3dFJBp6QNELosakLa0rUQA6NeBsAy6ZFHzPBhw1LtE5A7BlQtrH6MzWjBKddlDdg49Ch0TaUGLvm4t912mzVASPKQLiirinHCDBbS/fdPMCNGDM+kww6gxaLfZ599bBL3jjvuWNJjeFXNvRBQSzMKg9VxAd6ZZ55pLrjgAievghABFw36JN6DtHQvVwaUxRB2A0A1b9682FG9OO+WDjIsVroA7bbbbrG9MXGeX17XBC1xkRqNGjUyHTt1cu5mEyVwEl0rC0aJqjJ16uOmV6+eK0WlkrwP0GIEUh2NeoBum9bcC6lXvh6JsuYbNHBxp+BrvPjii20Uy4cJce8pFBhIc4uVMdHYjwoPKjSSGmrSBRzvAZL2qKOO8qJX7oIvSyeOA+QkNAseuOimADdJQ4l8q9rFWCnELBdpKc966OGHbTdJfJSFFk++54sHoW3btjbSmHSs0QWP7xQfMD5wEp/oCfZTcbGNOlb95wgvPDX4a1lAuPqivmwfACtwc7hdGkP5m4R/+TmaTAMjMOpwpyVlRnQokhtBUIJ8jCTdJKVrDMEUqgXItYi705Smg8tixmVHSijHEbzwwgs26UkScrAfeAe0kcQahAsBDjwZGIbkOLiE6ktT74L046IqpClxo8xEgvB8dELCku+//75Nf1y2fLlZXFxsGQThCYciSWhoQVcWwo4SfnaR1mUZaRhndHr59NNPvdQFUREYJ3otvlpf0EbHCE1oNAdokbiAOApUyffgb3wJkFnggBnV7oQTTrBf/CzXx92VVOJG8kqRmHgZkCKvvvqamTnzeQtaiM7/RNJGpbKk/sE8MsRgxIknnmgTcZK410oYU1xs20TR8ILnu+YxMD4WH72EAa7Pthz1uLCgn3nmGUOHRHRwpLkkGvFsAWouAOW9jF+OsoVmJO6Q3eXbjajSSlwBCKoARtDMmTPNk08+aaWrhHyRBnwJSHO3LFEf+I7k4dBAInD0e0jSIUfG9uC//21u7NXLtlN1Aa60OWJ77tmzp3d/LhkHgCMkPXr0aEsPSTgqC6xlSc/oYkcv5oBEwOuyE6jENcZWCwNWcgWQtnIsZ1Q6FTKMoteSsMKWiIRDArswpDQ9l2YX1MaxpcYFruwQaZyzION/9LHHzM2DBtn5pHG6jSysVq1aWQPbhU6VGriA4J133rHRM4wgMRZcJUiuZGH7JHGFiBT6KWqDC1PkeWKgsTXTO4Bc2Lgf8dliiNFbi7H4jEHuwfjq06ePnReSNu4Cyjde6SxPqJ3GLC7jq5TAjaoHd911lwUu/k3R5eKCI991kgtAEg/ZZnGSrnOfJ8BFfaHVVGmqSr7tGPUHf+11112XqHEygZ6rr7rKvPb666mmDkITdjj0b/zVCtwCyBMCsaWjs9FKHyL6Gi6lvY5nYcjgaYApVFC4MIZnCnCpp0JHZbxxzmKTd+NqQuLTrt7nE9WxR40caR8R5/1x3wXNMfBOPvlk07t3byf6VGqJm+XhJYAH/ZIvvAJyWLaL20eAS3b/jTfeWJI3HEffRtqSh9Cvf3+vcLgAgxo52lyR8J1mojbglnb6uOgAroshq8DN8NQdiIt7jRMwKb+OFhTGkUrCHLL7YSzSqVDoN7pgOnTsaJqeemoiNYXI3bChQ72eUWiOcuzXoYceancGkp3i7kpyHb52WhRQRZLmwsqsrwKSyzcAEVUVsj4uCnUBvy7uHvywcRkT9Z1iQNIDFulXqDIC4IrfmYNZdtppJ6d3RsHG2DnKCW9Lms025B0S0aMYEz0cN2Jc+sh1fKdY8tVXXw2jPD0E4AIitmxhDAZgXMZEdVyYgo6Lj7iQjin6LS3qBw0a5BXelTG++eabpl+/fok7/ZQleZMAN/rM4MrTK7rEFRBtveXWZtAtg8zmm7mdxxY1zjDwkICFgAtDuY7gB9WvLttvrhtuwgMPmIEDBtgwdhrur9LchngsyA2mwXbNmjWdFrY8L7jy9FCAi16K223rrbd2YoyPV0H06s5duphTmzTx1quR7tS+PfDAAzbwkVb1bBS80cgeflzfpHYFbpUqhewJp/+LvgkA8RUTl/dRFXCHYbwUUhXEMMNbgieDRHGXTu1RvZpOmJxIRE8uIolZSFwJkhAcITJIhbULfYKWuCSSsyW65OOWl3EmwOV9gwcPdk4kEdARtSIAwUcad5TlO8YwI1rGoXU+Z4cJbbDSiZTF8WQ4rebIxQLcHXbYwQLX98io4CQu+hHOa6JTUp0bJ4iwKoDLtksOqotEEeByDhshX9Il833EGETS0uzY9YzjqEHoE61zBbCkXDLOLl26eB8ZFRxwybQnQaNdu3YlRwVVNOBKCh/WOQnUWQMXNYH+EPg2XXahXMOMxB66tSetvIiz0NChSZanP5kLfeTZwXkVAK5P7zCZMNY3hxeTpiddEwtFpVykCotIOhciMbH04yysXBCRZEPlQhyJS+5t48aN7WJO4lF4/PHH7cF5+Faz0G9F7WGhodoA3MMOO8wLuEE1dk7SO0yAgaU8pajI9O/XL5P+BVHgsnWjj/sAFxChA1JpkQ9EPJv81jPOOMOce+65TrtQ7mIhYtazRw/nHGCXhS2qQlLgVjqJCwiKpk41ffv0yRy4bLuUGfkAl7ZMSD/cafncUjwbFyGMJCPNp55Lturx4+8zAwcOcMoBdgEt14qfGz8xBja9y3xUBWjL4SXYOWntDpmGfJOqCoAA4FJFK200s1AV/l7xt7n+uutN3bp1nXgrxhnAReIW2rYBAjS5+pprTJNTTvECgQBn3LhxNvLmkrzuNLl/gIsqRVvTjh07mQYNTvIac1DHRaWhKgAMVIUsgStFgvhEDzjgACfGRIGLxCU1spCqQHcffL4nneQHAgEuUTMO6CZHIS0plgtsUaUALofI+I45qAP6QgPukCFDnDvH5AI3jqoAcHv27OUtveSdU6YUmW7driwo5V2lbPR6Ba5jR/KoIVJeEjcJcF2MM3zbhHvp8O2S+5trnPFOauYKSXkFriMFKpPExfDAKyFpkWWRCglGTRgeBY7QknMlfAzCGTNm2GidnJDjyJ5Yl6clcYM6WTI04N5yyy02vdHFao5GzjBA0AULOfRxh9HzlzZLFH+6vI9nR5PXCZpw7Gyh5PVYKC3lIsmtYHG079DBJgW5jpfHkmRfVFS0UiMW3zHJfZl7FXD7cHgJFbCuky4P44wgB+PioA7Xal+fkC8VF9LdR6JeLhJXaEgPMPIrkLw+jUhcgINn4cJ27bzPOsP7MXny5FTbsWYOXJztABdpVJGBe//99zsXTPoAl0gUoWW8EL49woSOw4cPt1lt5BJkkdYo4E4KXBKK6PQjqpHLoilT7apXr96KNB6U+wxUBbrNkGDTpk0bZ9DyvPKUuJQIuSZK+wAX9xuVFkghVwmfa6BNmzbNZpkxDhep7crvSgXcJCdLRgk7ffp0W+/Eao1TXeDCFIkMIcEog/dNJHfJDgNk6LlIy9q1a3staJG49Dyg5oyc3DQLEXNpmBS42A/UxflECleJxPU9yzdqhMAUUuqyBC7vQ+JmDVxhAgnnHC+A/i+GlavEFPCiKlB0mebhd2kDlwZ8CAY++fKVnYROlqpCWsAlBRAdOSuJy7MhrmtTEFdVQRiDQYieG01L9AUu3Srp6UBDQLLNstB1k0pcFhY2BHMMArjouDRLw2/papjJ9UjcrIGLtKKUhuwul3H6AFfUE0A2atQop5LvXIkkYx07dqy58847S5pLp5nPwTsBLmmY5Fa70EfGS14FY4ReaQmfzLwKDBAdrFu37ub0009znnB5ApespZEjRzqDyBe4AAHJSGUwXWJcpa0AQmjEyZtI77fffjsTXTepxH1k8mRDiyhaAUhPYhe1oLRrMwUuBX039e5tu8T4FgWWh8QlUYXSHddSGpmTa7dGKeHZ/4ADTK+ePW2xo48ki9oCdLMkeef777+3gY00VAZZUCS/czQthyT6jPPhiRPNbaNH27L8YIDbu08f07hRI2/g0goe4yxLHZdiQKJQrn5VAS71X3g+pLl0IWnCdUgfetjiFXDt9l2WyiDuMYIcEvDxURsALF/cy+mWVD8j0TmI2ge4jItcELwpaUX5KrzEZftjtWcFXABEwwu2bdcaMAEuuwKN5+I2BIkaaZQLAQpp3eSjNgiY2NI5rnXM7bfbnAihmfjE8y0oAavkJ+BvZj6UpCM46Kng+yG6Rw9gkujTaDjNOCoscAUUWM1sUTAhrW0myoAkFr6M0bXNqLiF2IKR8gQjkPo+0iwXTKgIdI+kTm/u3LkWfCwKORVIdgXeFf0C9Cxi5oTrEYOVxHqaOpMgn+QjwCUzLq2m05kD11dVKE/gyiGCrsWLSYAblboNGjSwnpM0HPTRXAYSW1hU5DWwTQNMJCkglUNNeCc/oxdT7Ekgg/4JDRs2tO7BJAe8yBxZSOxIGJEIoDQS3zMDLiubgUq2v6txVl7AhZkc24q7x9VISgpc0XVhJqdJJjmPIuppsFvpP11/AOysWbPMnDlzrL6KCkG+BJKP9/IFYAk/ow4gXdM4oC9qOM6ePdv2HsOvj+5doYErFa2sNLKhkgCXg6whbhaqAlGs1q1bW3XENT82KXBhLtKOLRTQ0PHRNV+irC08qdohRp2Pzp3rrvvkk09sTR5dd5DslQK4HIDHcUVycJyPlZyPuQCXQsDmzZs5ddwWgwep6aPjRsckLVnpt4DKwFyTAi8XPHF01DTAGn2PzIFAFJXNn332WWrRvcxUBcn2R+LWr1/fW+KyWkmLRC9LW+JCWFxH3bp3Nw1PPtm5lCYNiSvbuuiddCmXhO3olh8HeBXtGgEuRiiJ8/Pnz08tQJIZcCEizMC/iXXqqirIpBcsWGArTJl8oW7fLoxjYTEmgIsejlvKVcoldYflSl2kP+Xm9DCQ09MrAnh9JbHQE4OQsD/5FGklA2UCXCn5AGiUtNArKwlw8eNiUGQBXIyXoUOHmjp16ngD97XXXrOJLhg+SXYF9F18nUTyUBmOPPJIO6ZVBV7XhZwrOOR+XHLkZXPkQFrVGhUeuBzuzKQBRdrAxefJc0kA8Tl1RxjjcgZEoV1BwIt/F8c/4BULvTwBHAXtBx98YA0reocVqqsrTccFuFQkczJQWr18KzxwKQbEIiVhJwvgos6QdrfLLrt47wr0qqUgkDGmEdKUky8BL246VK3oc5NY+vkWTtTwlXyKJ6dNM3eMGWPdZHQld+npG1UViEw+99xzqRVMZgpcXFiEM1mpSDcXgjNpGIglSnlz2tWsEtoEECTYAFzfMRKWpskyfsq0Fpc0nEPCkbuLZwVfq6QFCihcaJrPuxKV5qh1eAI4XoAEIn4m9IvUpIdw3FKhqKpATgZl/C5npeVbZJkBl+2BbCt0XJ9O1tEIEBJ34cKFqUgzIQYMx2hAnySO7uM/lTHi3McHm3Z3cMALHYWWTZs2MyeeeIJtHifNRCRsGwVwPjCLVJXv0aYkBGPobfbyK6+YSRMnWi+AuOYwGuGDT7kR76JU6aGHHrILL41k8syAyxZM+LBNm7Zmr732tOFGF+nAZFmdgIGaJVZ9EsMnd/WKxKVwESse4AIQ1zHCWHTAMWPGxD5ZspCem+ttgBbQjw+6OGfr1qpVy/pEoyDO1S9zt/7S5gaf0POhL0cCPPHEE3bn4F4JB7PAiXi1b9/BHH30UfZ6eZY0xhYvDb9LZpmkVvKsCRMmGGrzXA9BLItWmQA3+jIILoBwCR7I5Jko26ULoFyAwbW4xERN8BkjC8rFaHEdH9cjpSQBHXriVqJJ34F16pgdtt/eCgkWEYtdEpJy38N98AMPDdE6+pjNmzffzJnzgU3M4XcBqwAsSg8OE6RK5KfiYvPnH39YnuCV4bkSvsYrwr2Mlf8Bev4XzVTzmf//CJ6sas7kRehDLmAoTTL69NhyIU4IY4zqoCwyaAo48P2i7tTaeWdTvVo1625CEm+08cZm/apVLWiWL//FLFm6xCxdssRKS9QBMsfw2PAB7Cw+ro2qILk05H0AMSo186ko0f/FzVWOy7fMJW4akjIJ8OMQIoQxRucRHS+0YeEBKADNz3xHCspWDWgApuiXfBew5rrYCtHal1aFnhuHTyvRIGuJ6zogvd6dArlgimOc8Za0weQ+cv87Mpe4/kPTO5UCZVNAgavoCJICCtwg2aaDVuAqBoKkgAI3SLbpoBW4ioEgKaDADZJtOmgFrmIgSAoocINkmw5agasYCJICCtwg2aaDVuAqBoKkgAI3SLbpoP8DI8jhB+18gcUAAAAASUVORK5CYII=
openapi: 3.0.0
paths:
  /:
    post:
      description: ''
      parameters:
      - description: Generated by shuffler.io OpenAPI
        example: api_key=apikey&hash=838DE99E82C5B9753BAC96D82C1A8DCB
        in: body
        multiline: true
        name: body
        required: false
        schema:
          type: string
      - description: Header generated by shuffler.io OpenAPI
        example: application/x-www-form-urlencoded
        in: header
        multiline: false
        name: Content-Type
        required: false
        schema:
          type: string
      requestBody:
        content:
          example:
            example: api_key=apikey&hash=838DE99E82C5B9753BAC96D82C1A8DCB
        description: Generated by Shuffler.io
        required: false
      responses:
        default:
          description: default
          schema: {}
      summary: Hash status lookup
  /e/hashdd/{feedname}:
    post:
      description: ''
      parameters:
      - description: Generated by shuffler.io OpenAPI
        in: path
        name: feedname
        required: true
        schema:
          type: string
      - description: Generated by shuffler.io OpenAPI
        example: '{ ''entry'': "http://buithiyennhi[.]com:80/smt/loki/fre.php ^8e3951897bf8371e6010e3254b99e86d
          #lokibot -- C2 for lokibot", ''api_key'': ''apikey''}'
        in: body
        multiline: true
        name: body
        required: false
        schema:
          type: string
      requestBody:
        content:
          example:
            example: '{ ''entry'': "http://buithiyennhi[.]com:80/smt/loki/fre.php
              ^8e3951897bf8371e6010e3254b99e86d #lokibot -- C2 for lokibot", ''api_key'':
              ''apikey''}'
        description: Generated by Shuffler.io
        required: false
      responses:
        default:
          description: default
          schema: {}
      summary: Posting observable to feed
  /e/hashdd/{feedname}/get:
    post:
      description: ''
      parameters:
      - description: Generated by shuffler.io OpenAPI
        in: path
        name: feedname
        required: true
        schema:
          type: string
      - description: Generated by shuffler.io OpenAPI
        example: api_key=testing
        in: body
        multiline: true
        name: body
        required: false
        schema:
          type: string
      - description: Header generated by shuffler.io OpenAPI
        example: application/x-www-form-urlencoded
        in: header
        multiline: false
        name: Content-Type
        required: false
        schema:
          type: string
      requestBody:
        content:
          example:
            example: api_key=testing
        description: Generated by Shuffler.io
        required: false
      responses:
        default:
          description: default
          schema: {}
      summary: Get Entries from a Feed
  /f/{indicator}:
    get:
      description: ''
      parameters:
      - description: Generated by shuffler.io OpenAPI
        in: path
        name: indicator
        required: true
        schema:
          type: string
      responses:
        default:
          description: default
          schema: {}
      summary: Get Entries from an Indicator
  /nsrl:
    post:
      description: ''
      parameters:
      - description: Generated by shuffler.io OpenAPI
        example: api_key=apikey&hash=838DE99E82C5B9753BAC96D82C1A8DCB
        in: body
        multiline: true
        name: body
        required: false
        schema:
          type: string
      - description: Header generated by shuffler.io OpenAPI
        example: application/x-www-form-urlencoded
        in: header
        multiline: false
        name: Content-Type
        required: false
        schema:
          type: string
      requestBody:
        content:
          example:
            example: api_key=apikey&hash=838DE99E82C5B9753BAC96D82C1A8DCB
        description: Generated by Shuffler.io
        required: false
      responses:
        default:
          description: default
          schema: {}
      summary: NSRL RDS lookup
schemes:
- 'https:'
securityDefinitions: {}
servers:
- url: https://api.hashdd.com
