openapi: 3.0.0
info:
  title: InsightIDR API US
  description: Insight IDR API V1 Get more info at
    https://help.rapid7.com/insightidr/en-us/api/v1/docs.html#
  version: "1.1"
  x-logo: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK4AAACuCAYAAACvDDbuAAAAAXNSR0IArs4c6QAAFydJREFUeF7tnXecVEW2x3+3c/d0mBkGBBFEQST5wYCw+sEImAWRXUVFQJQsi0gcVFQEVMABRPeREZ58wNW3LD5WjCirz32oKC6IgGCCJ4gTOqcb6n2qh1nBJXS4t7vu7br/7I5UnVvnnG/XrXDqlEAIIeAPt4DOLCBwcHXmMd7clAU4uBwEXVqAg6tLt/FGc3A5A7q0AAdXl27jjebgcgZ0aQEOri7dxhvNweUM6NICHFxduo03moPLGdClBTi4unQbbzQHlzOgSwtwcHXpNt5oDi5nQJcW4ODq0m280RxczoAuLcDB1aXbeKM5uJwBXVqAg6tLt/FGc3A5A7q0AAdXl27jjebgcgZ0aQEOri7dxhvNweUM6NICHFxduo03moPLGdClBTi4unQbbzQHlzOgSwtwcHXpNt5oDi5nQJcW4ODq0m280RxczoAuLcDB1aXbeKM5uJwBXVqAg6tLt/FGc3A5A7q0QMHATe7bAeXngxCsFl0aLt+NFjxlEBxOmFweCCU+mNy+fDeBqfcVDFwSCcA/dwSS2zYCggwoAiAAoHcAmQHIR+3U8Ldykr/pf26o1/D/6f+ajspo+Df6d7oyTiSTtqNBRoNs2s4Gmb+tczIZDe4/VhaV0fD3sbocK6PhbiRqJncZzE3Og6m8Oaxt2sHUuBUszdvA3LgFTL4yCDYnIFBBxn0KBi41qXzkIEIrn0Ry+3tHPWdcQ6uumSIDRAKUOGByQHB4YW7eHJaWnWFp0wW2jl1hadoSMNFfl/GegoILQiAd3IfA0wMh1xw2rJHzgw0BKMyCCRAUCHY7bN36wXnNH2Bt0xGCxZafZuTpLYUF96iS4jfbUTftVkCxcHjVcjy9d1FOgkhR2C69Fe6+w2Fu0QGmEk893Dp/mACX2jCxbTOCC0aAJEVAMObnrTCsEECMgChx2Lv1g6N7X9i79IBgdxamOSq9lRlwiZhE5LX5iL6+iI93VXLuv4lRJAhOG2ydr4f73kqYK87U6k2ay2UG3NRkrfoQAnMHQ/puD2Diy2RaeZ+IMQhmAd6xS+Do2guwWLV6lWZymQKXapn86hP4n+oNwGWIsZhmnstVMKGrEjKcPe+F67ZRMDdunqvEvNZnDlwoCiIbVyC8YhIEZ3lejVF0L0tN4OKwtr0YJQOnw9b2Qt2s/7IHbmrMIKH20X6Q9n0OWOxFx1PeFVZkmDx2eEYthv3iK4/u6OS9FRm9kE1wU6sM7yE4fxSIKOmmF8jI8qwVVkSYfBXwjlkIW6fLmLc5s+Aq4QBCyx9F4h90S5gvj+WFczkJk68R3A/MhuPSa5leU2cWXLqrltjxDwRnDwCR9b9gnhfw1HgJXTJze+AZVgVH157M9rzsgkvjbSQRgaqxSH66AbDoe8FcDabyJoPIMDc9G96H/gPWVu3z9tpMXsQ0uFQR6YfdqJlwDQSLSxeThkyMz3JZIkZh69ANvvHLYfKxt7rDPLg0cMQ/fywSH/0Zgt3Lsq+N17ZkGPYr+sM7YhYEB+042HnYBxeAuHcbaif2gOCqYMdyRdISEv4entEvwXXDAKY01gW4SrAOgQVjIO78SNutYHJsVDhTfsq+MamA8tyCyk2lHvgeWg5r24uYmazpAlzIMiJ/W4HIK3NAd9Y0ecw2CO5GEAwWeE1ifpBYMLftc0WCveuN8I6aC8FZoon5MxWqD3BpDMPXnyFYdT+UcCRTHU9fXpFgPrs9vEOfZXIicnoFTlZCQOD5sZD2bgXMuexAEpBkGKWVa2Dv0jP75qhYUzfgKvSM2qwBkPbvVH9DQk7A3rUXvKOeh+Byq2jewoqSDnyD2spbUlvouQ4XQNd3y89CxXObILg8hVWMakMIjbTQxxNevwzR1RMBRyN1G0xkuHoPhbv/FMBknM2O4JJpiL/1J8BWqo69EjVw3f0U3H1HAObChp3qCtzUmu6DHSG4z1HHEQ1SzGZ47p8F5zX91JVbQGlyzSHUjL0akOiJErV+jASm8gqUTlkDS4s2BdROZz0uiYVRPe56EP8hFZ0BmNwO+Ka+Cus5bO4SZUNIZMNShFdOVj80VABK+k9Bya1DVPVBpjrqqselygVXzkTs9XkQHCp9/giBuXE5yp7aBFOpMdaJSTKOusdugPTDAfWXrxQRltad4Ht4GcwVzTLlTbXyugM3uesT1FXSzYgz1DGCnISt8zUonbK84OM2dRQCkrs/R3DeUCjBgFoij5FDUj8G39iFsHe7UQP56YnUHbh0uHDknnMh2OnMNreFdWoiEvejZMAMuPuNSM9irJeSJUReq0LkLy8AJo1yKUgx2C//PXzjFhTMGvoDV0yi7ol7IO37VJVdNBI7hPI5H8N6XueCOUHNFyvBWvjnDoX09VbA4lBT9HG9Lon+hCZrjxRsaUx34NI1yeCiSYh/sA5IRYzl8NAtXpsHFQs3pwKojfAkd22Ff+Y9gFz/SdfqIfFf4HlgAVw3D9bqFaeUqz9wiYLI+oWIrJ2Te48iJWHpeDXKH3+poDNkNT0fXDQVsXeWQ7BpvEkgJ2Fu3QXlT6wpSHIRHYJLEHv3ZYSWPgKYcxvD0V6jZMAsuPuNVpOdgslS6o6g9uGeUGLhvPwQSfxnNFqwDZaWbfOus/7ApQcpv9iCQNVIQErkNkGT4ih9/NX6w4EGeCKvr0T4pcn5i1uWwnAPWwBXrzty80MWttcluMldnyIwbxRIuDZ7gxEFgqcC5TNeg/mMllmYjq0qJB5NxSXIh77PS2+b0p7IsF/eB97hT+d9uKBLcMVvdyFQNQxKNd1By3ICIidhafc7lE1ZYYjAmuTO/0Xg2btBJLW2d9P4YRICa+v28I1fAVN5kzQqqFdEl+BKh75HsGo4pAP7sgdXjMB5/SC4B0+HYM1trKyeO7KUJEsIvzwT0U2r8tfbpnpcAlNpOXzjl+V9OVGX4Cq1hxGYNwziNzTEMdsehsAz+HE4r7s3e/iz5EztanL1TwhUjYC0f0fecyEINge8o6tSYaFqbAilaxt9ghuoQaBqEMQ9X2Udm0svAPGOWQB75+7p2orZconP3kVg/oOALOYVnnqDEHgGPQ7n9QNy6EQyN60+wQ35EZg3FOKubVkaiwbWNIJv0lpYzmqdudWYqkEQXDIV8beXA9YCnIKWE3D1GQl3/8mAOX8Zh/QJbjiA4PwRSO78JLvPPFFgbdMepVPXFWzLUi32Ff8R1Iy/DiSS47mybBskxWHvfju8o5+DkMc8u0ULLl0Cs1/WJzXB0PJREnE4L78JVprCU4MnsnEVwismQLAX6N4zOQFr554onbQIgjWXc22ZGac4waU2UiQQMZ6ZtbIpTZJo9MKnsDRXf0hCrx+o+eNVUOoOZz3Wz0al4+oQGaaKVmg09295TRqiT3CDtQg8NzCnyVnODktDAD0Z6+g5BL6Rs9IonXmRxGebEZjZB3CoFJuceRPqv1hSEI1X74fgyt8YW7/gVg2BuPufWU7OsvFQpnXoEERG2fQN2qxx0oSAz49CYus7qoR3Zqrdr+UJSPgImqw7mLqqNV+PPsGt/RmB+cMh7mUYXCkOS8fuKKtcqcl2qPR/3yLwzF2Qf6nOboKqGmEEJHIETdZycE9rUunQDwhWPQDpwH52e1w5AffAR+C6eZj6bSQE8Y82ILS0EkSka7eFfDi4aVtf/O5rBOaNgHLkYIF7m5M0mR7AbNIstRVqObtd2nqlW5AkEwgtmYz4llcZyBvMhwrp+g3J3dtS90MogeoC7BSl0UxFhP2KfvCOeFaTtU35yAHUTbsDiv9n9XvzNNQ7vggHN22TJbdvQYBebJKgy1lZRoel/bYsCspReMevgqMb3b9X/0nlTFj1SP7ibk+pAgc3bQ/HP96I4AvjNN88SLtBxxakCfSanoOymethcquU++EY+SQeQe3U2yEf3A2YWbgRkoObHieEIPbmSwitnJZjBsL0XpdpqdQhwuEvapYIOf7Juwg8czcjvS21Dgc3PUYUGeE1MxHd8CJg1fhAYHot+rVUKqNhC1RUbYLg1Cbro3/GQCR3/L3Aa7fHGoYASgSNV+7lGxCn4iV1E8+CsUhu/W/2etxkAK5+E+C+e3KmyKdVXvz+awRm9IUSoWlDGXno0KjZeSh/ZgPf8j0luMk4aif2gnz4AEO9Tv1pAMHtRenEZbCef4n6VBGC6MYlCK+dDRCGJqQNQTYTF0Gw8SCbkzqeTk6O3NUMgqMxWysKNAfZxVfD++BCmNzqb30qIT+CL4xC8osP2frSSHE4rr4DnuHaLP2dDATdbfkmtm2G/8k+EEoKGFhyImsSCSV3VaKkz3D1e9vUzUNfwD9nKEiojq1NF0VCyR0Po6Tv6LweG9IXuERBeN0CRF6ZAcFZpgkgWQmlhwa9XvimroW1lfo7ZbRN4VfmIfrqbMDKxuUh/7KTAHjunwHntXfm9QelK3BTuQOm9IZ8aB9T41sixuDofge8o5/V5MQwHR7VTL4dyuE9TOlNl8IEpxdemnI0z2f3dAWufOQgqoe2Vy83blbd679XIvE6lM/9ANbWF6gk8XgxyS8+QN30vhDUvvsi19bSL01FU/jGL4X1nA65Ssuovq7AjX/8Jvwz+8LkbZ6RkpoWlmKwtL8KZdNWaRKXQJf//LPuQ3LHBxA0SxuapYXo2b0OXeAbtwQmj/q7hKdqlW7ArY+IegTxLa8Alvwtu5zWpVIU3gkr4eh2/WmLZlMguXc7/NN/D0japg3Npm00BZOj1xB4B1fmPZu7bsCVafD4jNsgHfolKxtrUoneh3DOhSid+hJMXm0mi6Hl0xB7ezVjY9uj1hSD8I5fDcdlN2hiXkP0uPR8VfDFh0AnaMw8NKfAbaPgvnOiJj2O4q+Gf84gSPt3Fe4w5KmMLQfR6IXPYW5yVt5doo8el+bGeu15RNcvZMqBJrcb3rGLYOv0O00cl9i+BcGFY0Ci9BpYhnbLqLZSHNZLbkbp+IWarKSczqC6AFehKZeeGw5xD733gYVQPnq8XYa1/SXwTViuyU4ZlR96+WlEN7wAwaZNwM7p4DjVv5PwIfimb4LjoitzEZN1XV2AK/24G7UTeh3NQM5Gz0OSEXiGzoXrhnuyNv4pwYiFUPvoHZAPfK3JMCSnRtPcwk4PGq/8MicxuVRmH1xCEH75GUTWz2MnBpXIgNWFRgs2w1yuzdZzYvuHCMzsz8CZshPgJYbhvG0sPAMqc2Evp7rMg0uiQVSPuQIkEmLgfNVRWydDcN42Hp4BEzXZ5kzdDDlzCKSvNgNWxoYJNArO5ULppBWwtrs0J/hyqcw8uJFNaxBePBqCk5HrSuln0upAedW7MDc+Mxfbn7SuuG8HaiddW7h8YKfSSpFhv7QnPCPnwpTHBCC/bRLT4NJJmX/mIEg/Zp8HV22yiBiB46q74BtTpbboenmEILRqFqIb/wTB6tTmHTlIFSxmuIfOhvPKPjlIyb0qw+ASxLa8jtDihwCSv7yrpzYpSU2UvGPmw6HRPbZy7RH4n+oH+fBP7C2BKRIsrTujdNIymEppPHThHmbBVcIBhBZPROLTd9kZ21LHtWqfWgLTapgQ+/tfEV4yEYTeDMnYQ0I/oXT6G7BfdJUmY/tM1GUW3OQ/P0Jg7jAQMce7zDKxxunKKkk4e90Dz5CZgCnbuydO/hKSiCG0ohLx918DzFrdw3s6JU/87zQlq61rH5RNejE7ASrXYhNcoiCwYAwS/7M+9/t6VTSYYAF8letg69BFRam/ipJ//hH+Z+6vjzcWWBke1d9nJjhdKJu+HpYW+b9F8kTGZhLc5K7P4H+iN2ByFvyT1GA0IiVg63w1Sicu0ST7In1P/MO/IvD8aAgW1iZlCkpuHwtX31GahG5m0wswBy6JhVE94WaQ6h/zeobpdMYjsWqUPb4BNjq+0+ipfXIgxJ3vQ2ApbJPG3La+AN7xi2Eub6qR5pmLZQtcRUb07bUILRoOwdksc220qiEnYD77QpQ/tQ6CQ5szX+L+HaibcuPRWGM2trVBFECIwjfpz7AXKCbhZC5lClzpx70IzB9Zfx8tQ9FQJBmCZ+gcuG4YqNVPA8Hl0xF/40XAxkp2HpoiPwHPyPlwXnM7Oys7Rz3ADLj0Io7I2tmIvrGcuYmJqfxMlD26GuYz1b+AhPpBrjmMusoboYSC7PxgxSBcff8I912VTA3ZGnoOZsCVvvsKddP6gogSW79umvDiyr7wDH1WoxRDBLF3X0Fo+SQAjNwpTETYOnWDZ9RCzYKIcv10MQGuEqqDf0Z/SN9+CVjYCioRrGZ4hs2Bo3vvXG19wvokHk5lqEl8uoWJWGM6LLKe3w3ekVWwtGijic5qCC04uHSDIbTyKcTfWsrQ+O5X05qbNkPZtP+CqUyba+2lH/cg8NwwyD8fKPiXhiSCsHa4Ar7RVTA3O1sNvjSTUWBwCeJb30No4TAQWf2dqFytRhJhOG8aBe8D03IVddL60U1LEV4+FbCqn28so0ZLUVjO7YTSKWtgKitsHEI67S4ouNKBPQguGAnp4HdsTcio5VJLQQTls9/SbrdIkVE3YzDEHe8DBcuZQAAxDNvF18M98AlYzjo3HW4KXqZg4Kby3D43AsnPNjG1rfsvjyT9sF81CL4HZ2s2qxa/3YW6R28FFLqYUIC1W0VKXQ3ruuU+OG8eCXOFNvHFWlBeMHADix9H/J3FEFiL8E9ZmaR63LJZG2E9t6MWdk/JDC6bjtib1AYF2OKl0Fppwrq5cFzRG4KFkRWNNK2dd3Dpem1s8ysIL3kQsDE6lpKTsF7YA6WTlmi2Ny/XHELtuB6gGXry2tvS83KCAEurTnAPfgK2thfl9/1pgnm6YvkFl96I+MlbCC+dACUSY2ex/bdWIiLc9z4G101DNJvpR99YjfCy8YA9j5MyMQJzs1ZwXHsvnD36w+QtPx0fzP57XsGlF8vVTu4FEqO9DENhe8e6hygwN24G78NLYD1Hm2GCEgkgMPteiHt2avbDOI44KQaSrIPz1olw9boTlrPasnfkPcOfSH7AJQTSgb2onXRTffMKMRFJ1zD0VsiuPeAbt1SzSVnyq08QfH4MlGBNuq3KvBxdFSESYBJh63wLPPc9BvMZLTOXw2gN7cElCsRvtiO45BFIP+xkK2TvhE6R4X1oMRzdrtPGZal0UvMR/ctClXfK6LVNcmqVALYSWJq3grX9FXB0vxWWVu0gWBnKcKmCZTUHV/rh61TvQq+ph8DeJsNxNlQkmCpaotFcek+ZNuGLJBKEf84wiLs+PpqZJzcv0iM1SAYg2GywnNcd1nZdYG17MaytOsHUuJnuVgvStYam4NKop5rhF4AQEwRWcn6dwjJKtBrecf8JV88/pGu/jMuJez5D7eRrIFi8mQ+ZFDE1ViWiDMFVBnOzC2A9vwus7S5KpbI3lTeFYDZrNsTJWFkNK2gGLs3GEn1rbf04jtWJ2AkM6+49BIIG1z01vCr55UeIf/ExBFvmyfvo597S8jyYm7aAyelOrQoIDpeGeLArWjNw2VWZt8wIFuDgGsGLRagDB7cInW4ElTm4RvBiEerAwS1CpxtBZQ6uEbxYhDpwcIvQ6UZQmYNrBC8WoQ4c3CJ0uhFU5uAawYtFqAMHtwidbgSVObhG8GIR6sDBLUKnG0FlDq4RvFiEOnBwi9DpRlCZg2sELxahDhzcInS6EVTm4BrBi0WoAwe3CJ1uBJU5uEbwYhHqwMEtQqcbQWUOrhG8WIQ6cHCL0OlGUJmDawQvFqEOHNwidLoRVObgGsGLRagDB7cInW4ElTm4RvBiEerAwS1CpxtBZQ6uEbxYhDpwcIvQ6UZQmYNrBC8WoQ4c3CJ0uhFU5uAawYtFqAMHtwidbgSVObhG8GIR6sDBLUKnG0FlDq4RvFiEOnBwi9DpRlCZg2sELxahDhzcInS6EVTm4BrBi0WoAwe3CJ1uBJX/H1g3t37d/R3GAAAAAElFTkSuQmCC
  contact:
    name: "Azgaviperr"
    url: https://github.com/azgaviperr
  x-categories:
    - SIEM
servers:
  - url: https://us.api.insight.rapid7.com
host: us.api.insight.rapid7.com
basePath: /
schemes:
  - "https:"
paths:
  /idr/v1/customthreats:
    post:
      responses:
        default:
          description: default
          content:
            text/plain:
              schema:
                type: string
                example: ""
      summary: Create a threat
      operationId: Create_a_threat
      description: Create a private InsightIDR threat and add indicators to this threat. The following threat indicators are supported in the request body formatted as json. The maximum file size is 50MB.
      parameters:
        - in: header
          name: Content-Type
          multiline: false
          description: Header generated by shuffler.io OpenAPI
          required: false
          example: application/json
          schema:
            type: string
        - in: header
          name: Accept
          multiline: false
          description: Header generated by shuffler.io OpenAPI
          required: false
          example: application/json
          schema:
            type: string
      requestBody:
        content: {}
  "/idr/v1/customthreats/key/{key}/indicators/add":
    post:
      responses:
        default:
          description: default
          content:
            text/plain:
              schema:
                type: string
                example: ""
      summary: Add indicators to a threat
      operationId: Add_indicators_to_a_threat
      description: 'Add InsightIDR threat indicators to a threat with the given threat key. The following threat indicators are supported in the request body formatted as json, stix_xml, or csv. The request content type is expected to match the specified format: "application/json" for "json" format, "text/xml" for "stix_xml" format and "text/csv" for "csv" format. See request samples on the right. The multipart file upload (with multipart/form-data content type) is also supported by the endpoint. The maximum file size is 50 MB.'
      parameters:
        - in: query
          name: format
          description: The input format
          required: true
          schema:
            type: string
        - in: path
          name: key
          description: Generated by shuffler.io OpenAPI
          required: true
          schema:
            type: string
        - in: header
          name: Content-Type
          multiline: false
          description: Header generated by shuffler.io OpenAPI
          required: false
          example: application/json
          schema:
            type: string
        - in: header
          name: Accept
          multiline: false
          description: Header generated by shuffler.io OpenAPI
          required: false
          example: application/json
          schema:
            type: string
      requestBody:
        content: {}
  "/idr/v1/customthreats/key/{key}/indicators/replace":
    post:
      responses:
        default:
          description: default
          content:
            text/plain:
              schema:
                type: string
                example: ""
      summary: Replace indicators for a threat
      operationId: Replace_indicators_for_a_threat
      description: 'Replace InsightIDR threat indicators for a threat with the given threat key. The following threat indicators are supported in the request   body formatted as json, stix_xml, or csv. The multipart file upload (with multipart/form-data content type) is also supported by the endpoint. The maximum file size is 50 MB.'
      parameters:
        - in: query
          name: format
          description: The input format
          required: true
          schema:
            type: string
        - in: path
          name: key
          description: Generated by shuffler.io OpenAPI
          required: true
          schema:
            type: string
        - in: header
          name: Content-Type
          multiline: false
          description: Header generated by shuffler.io OpenAPI
          required: false
          example: application/json
          schema:
            type: string
        - in: header
          name: Accept
          multiline: false
          description: Header generated by shuffler.io OpenAPI
          required: false
          example: application/json
          schema:
            type: string
      requestBody:
        content: {}
  /idr/v1/investigations:
    get:
      responses:
        default:
          description: default
          content:
            text/plain:
              schema:
                type: string
                example: ""
      summary: List investigations
      operationId: List_investigations
      description: Retrieve a page of investigations matching the given requestb parameters.  The investigations will always be sorted by investigation created_time in descending order.
      parameters:
        - in: query
          name: end_time
          description: An optional ISO formatted timestamp.  Only investigations whose createTime is before this date will be returned by the api.  If this parameter is omitted investigations with any create_time may be returned.
          required: false
          schema:
            type: string
        - in: query
          name: index
          description: The optional 0 based index of the page to retrieve.  Must be an integer greater than or equal to 0
          required: false
          schema:
            type: string
        - in: query
          name: size
          description: The optional size of the page to retrieve. Must be an integer greater than 0 or less then or equal to 1000
          required: false
          schema:
            type: string
        - in: query
          name: start_time
          description: An optional ISO formatted timestamp.  Only investigations whose createTime is after this date will be returned by the api.  If this parameter is omitted investigations with any create_time may be returned.
          required: false
          schema:
            type: string
        - in: query
          name: statuses
          description: An optional comma separated set of investigation statuses.  Only investigation whose status match one of the entries in the list will be returned.  If this parameter is omitted investigations with any status may be returned.
          required: false
          schema:
            type: string
      requestBody:
        content: {}
  /idr/v1/investigations/bulk_close:
    post:
      responses:
        default:
          description: default
          content:
            text/plain:
              schema:
                type: string
                example: ""
      summary: Close investigations in bulk
      operationId: Close_investigations_in_bulk
      description: Close all investigations that match the parameters provided in the request body. This api returns the number of investigations that were closed and a list of their ids.
      parameters:
        - in: body
          name: body
          multiline: true
          description: Generated by shuffler.io OpenAPI
          required: false
          example: |-
            {
              "alert_type": "${alert_type}",
              "from": "${from}",
              "max_investigations_to_close": "${max_investigations_to_close}",
              "source": "${source}",
              "to": "${to}"
            }
          schema:
            type: string
        - in: header
          name: Content-Type
          multiline: false
          description: Header generated by shuffler.io OpenAPI
          required: false
          example: application/json
          schema:
            type: string
        - in: header
          name: Accept
          multiline: false
          description: Header generated by shuffler.io OpenAPI
          required: false
          example: application/json
          schema:
            type: string
      requestBody:
        description: Generated by Shuffler.io
        required: false
        content:
          example:
            example: |-
              {
                "alert_type": "${alert_type}",
                "from": "${from}",
                "max_investigations_to_close": "${max_investigations_to_close}",
                "source": "${source}",
                "to": "${to}"
              }
  "/idr/v1/investigations/{id}/assignee":
    put:
      responses:
        default:
          description: default
          content:
            text/plain:
              schema:
                type: string
                example: ""
      summary: Assign user to investigation
      operationId: Assign_user_to_investigation
      description: Assigning a user to the specified investigation. The user must be a platform administrator, product administrator, or read/write user with access to either InsightIDR or InsightUBA
      parameters:
        - in: path
          name: id
          description: Generated by shuffler.io OpenAPI
          required: true
          schema:
            type: string
        - in: body
          name: body
          multiline: true
          description: Generated by shuffler.io OpenAPI
          required: false
          example: |-
            {
              "user_email_address": "${user_email_address}"
            }
          schema:
            type: string
        - in: header
          name: Content-Type
          multiline: false
          description: Header generated by shuffler.io OpenAPI
          required: false
          example: application/json
          schema:
            type: string
        - in: header
          name: Accept
          multiline: false
          description: Header generated by shuffler.io OpenAPI
          required: false
          example: application/json
          schema:
            type: string
      requestBody:
        description: Generated by Shuffler.io
        required: false
        content:
          example:
            example: |-
              {
                "user_email_address": "${user_email_address}"
              }
  "/idr/v1/investigations/{id}/status/{status}":
    put:
      responses:
        default:
          description: default
          content:
            text/plain:
              schema:
                type: string
                example: ""
      summary: Set the status of an investigation
      operationId: Set_the_status_of_an_investigation
      description: Set the status of the investigation with the given id.  This api returns the investigation with its status updated to the new state.  If the investigation already has the given status no change is made, but the investigation will still be returned.
      parameters:
        - in: path
          name: id
          description: Generated by shuffler.io OpenAPI
          required: true
          schema:
            type: string
        - in: path
          name: status
          description: Generated by shuffler.io OpenAPI
          required: true
          schema:
            type: string
      requestBody:
        content: {}
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-Api-Key
